version: "3.8"
services:
  backend:
    container_name: backend
    build: ./Backend/
    #ports:
    #  - "3000:3000"
    environment:
      - PORT=3000
    restart: always
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=http"

  website:
    container_name: website
    build: ./website/
    restart: always
    #ports:
    #  - "80:8000"
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.website.loadbalancer.server.port=8000"
      - "traefik.http.routers.website.rule=PathPrefix(`/`)"
      - "traefik.http.routers.website.entrypoints=http"

  database:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MQTT_HOST: "${MQTT_HOST}"
      MQTT_PORT: "${MQTT_PORT}"
    volumes:
      - db_data:/var/lib/mysql

  traefik:
    image: "traefik:v2.5"
    command:
      - "--providers.docker=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=WARN"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/conf:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

volumes:
  db_data:
  mosquitto_data:
  mosquitto_log:
