version: "3.8"

services:
  backend:
    container_name: backend
    build: ./Backend/
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: always
    env_file:
      - .env

  website:
    container_name: website
    build: ./website/
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - backend

  database:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
