version: "3.8"

services:
  backend:
    build: ./Backend/
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: always
    depends_on:
      - database

  website:
    build: ./website/
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - backend

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
