openapi: 3.0.0
info:
  title: Stripconfiguratie API
  description: API voor het configureren van LED-strips.
  version: 1.0.0
servers:
  - url: http://localhost:3000/

paths:
  /leds:
    get:
      summary: Haal de huidige configuratie van de LED-strips op.
      responses:
        200:
          description: Huidige configuratie succesvol opgehaald
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LEDState'

  /effect:
    post:
      summary: Verander het effect van de ledstrip.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                strips:
                  type: object
                  description: |
                    Lijst van strips en hun respectievelijke LED's
                  example:
                    "1": "[1,2,3,4]"
                    "2": "[1,2,3,4]"
                effect:
                  type: integer
                  description: |
                    ID van het effect dat moet worden toegepast op de LED-strip. Dit is een integer.
                  example: 28
                delay:
                  type: integer
                  description: |
                    Vertraging tussen effectstappen (in milliseconden). Standaardwaarde is 0.
                  example: 600
                speed:
                  type: integer
                  description: |
                    Snelheid van het effect (in milliseconden per stap). Standaardwaarde is 128.
                  example: 200
                reverse:
                  type: boolean
                  description: |
                    Geeft aan of het effect in omgekeerde richting moet worden afgespeeld. Standaardwaarde is false.
                  example: true
                mirror:
                  type: boolean
                  description: |
                    Geeft aan of het effect gespiegeld moet worden. Standaardwaarde is false.
                  example: true
      responses:
        "200":
          description: Configuratie succesvol toegepast
        "400":
          description: Ongeldige configuratiegegevens
      examples:
        example1:
          summary: Voorbeeldgegevens 1
          value:
            strips:
              "1": "[1,2,3,4]"
              "2": "[1,2,3,4]"
            effect: 28
            delay: 600
            speed: 200
            reverse: false
            mirror: false

components:
  schemas:
    LEDState:
      type: array
      items:
        properties:
          index:
            type: number
            description: Index van de LED-strip
          state:
            type: object
            properties:
              on:
                type: boolean
                description: Geeft aan of de LED-strip aan staat
              bri:
                type: number
                minimum: 0
                maximum: 255
                description: Helderheid van de LED-strip
              seg:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      description: ID van het segment
                    start:
                      type: number
                      description: Start-LED van het segment
                    stop:
                      type: number
                      description: Eind-LED van het segment
                    bri:
                      type: number
                      minimum: 0
                      maximum: 255
                      description: Helderheid van het segment
          info:
            type: object
            properties:
              ver:
                type: string
                description: WLED versie
              leds:
                type: object
                properties:
                  name:
                    type: string
                    description: Naam van de LED-strip
                  mac:
                    type: string
                    description: MAC-adres van de LED-strip
                  ip:
                    type: string
                    description: IP-adres van de LED-strip
                  count:
                    type: number
                    description: Aantal LED's
                  rgbw:
                    type: boolean
                    description: Geeft aan of de LED-strip RGBW LED's bevat