openapi: 3.0.8
info:
  title: Stripconfiguratie API
  description: API voor het configureren van LED-strips.
  version: 1.0.0
servers:
  - url: http://localhost/api
    description: Backend server # Beschrijving van de server

paths:
  /leds:
    get:
      summary: Get LED configurations
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ledstrip"

    post:
      summary: Set LED configurations
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Ledstrip"
      responses:
        200:
          description: LED configurations set successfully
  /changeled:
    post:
      summary: Change LED segments
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: object
            properties:
              strip:
                type: object
                properties:
                  index:
                    type: number
                    description: The index of the LED strip
      responses:
        200:
          description: LED segments changed successfully
  /effects:
    post:
      summary: Set effect for LED strips
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: object
            properties:
              strips:
                type: array
                items:
                  $ref: "#/components/schemas/Ledstrip"
              delay:
                type: number
                description: Delay for the effect
                minimum: 1
                maximum: 1000
                nullable: true
              effect:
                type: number
                description: ID of the effect
                example: 0
              intensity:
                type: number
                description: Intensity of the effect
                minimum: 1
                maximum: 255
                nullable: true
              mirror:
                type: boolean
                description: Mirror the effect
                nullable: true
              reverse:
                type: boolean
                description: Reverse the effect
                nullable: true
              reverseDelay:
                type: boolean
                description: Reverse the delay
                nullable: true
              speed:
                type: number
                description: Speed of the effect
                minimum: 1
                maximum: 255
                nullable: true

      responses:
        200:
          description: Effect set successfully
    get:
      summary: Get available LED effects
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Effect"
  /db/effects:
    get:
      summary: Get all effects
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      description: ID of the effect
                    name:
                      type: string
                      description: Name of the effect
                    effectData:
                      type: string
                      description: JSON string of effect data
  /saveeffect:
    post:
      summary: Save a new effect
      parameters:
        - in: query
          name: query
          required: true
          schema:
            $ref: "#/components/schemas/Effect"
      responses:
        200:
          description: Effect saved successfully
  /loadeffect:
    post:
      summary: Load an effect
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: The name of the effect to load
      responses:
        200:
          description: Effect loaded successfully
  /deleteeffect:
    delete:
      summary: Delete an effect by name
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                description: The name of the effect to delete
      responses:
        200:
          description: Effect deleted successfully
components:
  schemas:
    Effect:
      type: object
      properties:
        id:
          type: string
          description: ID van het effect
          example: "9"
        name:
          type: string
          description: Naam van het effect
          example: "Rainbow"
          nullable: true
        description:
          type: string
          description: Beschrijving van het effect
          example: "Displays rainbow colors along the whole strip"
          nullable: true
    EffectInput:
      type: object
      properties:
        name:
          type: string
          description: Naam van het effect dat moet worden toegevoegd.
          example: "Nieuw Effect"
        effectData:
          type: array
          description: Array van effectgegevens.
          items:
            type: string
          example: ["waarde1", "waarde2", "waarde3"]
    Ledstrip:
      type: object
      properties:
        index:
          type: number
          description: Index van de LED-strip
          example: 1
        name:
          type: string
          description: Naam van de LED-strip
          example: "ic1"
        segments:
          type: array
          items:
            $ref: "#/components/schemas/Segment"
    Segment:
      type: object
      properties:
        start:
          type: number
          description: Startindex van het segment
        end:
          type: number
          description: Eindindex van het segment
          example: 11
        length:
          type: number
          description: Lengte van het segment
          example: 11
        effect:
          type: number
          description: ID van het effect
          example: 28
        color:
          type: string
          description: Kleurcode in hexadecimale notatie
          example: "#ff0000"
          format: hex-color
