openapi: 3.0.8
info:
  title: Stripconfiguratie API
  description: API voor het configureren van LED-strips.
  version: 1.0.0
servers:
  - url: http://localhost:3000/

paths:
  /leds:
    get:
      summary: Haal de huidige configuratie van de LED-strips op.
      responses:
        200:
          description: Huidige configuratie succesvol opgehaald
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ledstrip"
    post:
      summary: Verander de configuratie van de LED-strips.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  index:
                    type: number
                    description: Index van de LED-strip
                    example: 1
                  segments:
                    type: array
                    description: Lijst van segmenten en hun configuratiegegevens.
                    items:
                      $ref: "#/components/schemas/Segment"

              description: Lijst van LED-strips en hun configuratiegegevens.
      responses:
        200:
          description: Configuratie succesvol toegepast
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Ledstrip"

  /effect:
    get:
      summary: Haal de huidige effectconfiguratie van de LED-strips op.
      responses:
        200:
          description: Huidige effectconfiguratie succesvol opgehaald
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Effect"
    post:
      summary: Verander het effect van de ledstrip.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                strips:
                  type: object
                  description: |
                    Lijst van strips en hun respectievelijke LED's
                  example:
                    "1": "[0,1,2,3]"
                    "2": "[0,1,2,3]"
                effect:
                  type: integer
                  description: |
                    ID van het effect dat moet worden toegepast op de LED-strip. (https://kno.wled.ge/features/effects/)
                  example: 28
                delay:
                  type: integer
                  description: |
                    Vertraging tussen effectstappen (in milliseconden). Standaardwaarde is 0.
                  example: 600
                speed:
                  type: integer
                  description: |
                    Snelheid van het effect [0-255]. Standaardwaarde is 128.
                  example: 200
                intensity:
                  type: integer
                  description: |
                    Intensiteit van het effect [0-255]. Standaardwaarde is 128.
                  example: 200
                reverse:
                  type: boolean
                  description: |
                    Geeft aan of het effect in omgekeerde richting moet worden afgespeeld. Standaardwaarde is false.
                  example: true
                mirror:
                  type: boolean
                  description: |
                    Geeft aan of het effect gespiegeld moet worden. Standaardwaarde is false.
                  example: true
      responses:
        "200":
          description: Configuratie succesvol toegepast
        "400":
          description: Ongeldige configuratiegegevens

  /color:
    post:
      summary: Stel de kleur in voor de LED-strip(s).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                strips:
                  type: array
                  description: |
                    Lijst van strips waarvoor de kleur moet worden ingesteld.
                  items:
                    type: integer
                    minimum: 0
                    description: |
                      Nummer van de strip waarop de kleur moet worden ingesteld. 0 voor alle strips.
                  example: [1, 2]
                color:
                  type: string
                  description: Kleurcode in hexadecimale notatie (bijv. #FF0000 voor rood).
                  example: "#FF0000"
                brightness:
                  type: integer
                  minimum: 0
                  maximum: 255
                  description: Helderheid van de kleur (0 - 255).
                  example: 150
      responses:
        "200":
          description: Kleur succesvol ingesteld op de LED-strip(s).
        "400":
          description: Ongeldige invoergegevens.
  /dbeffects:
    get:
      summary: Haal alle effecten op uit de database.
      responses:
        "200":
          description: Succesvol opgehaald.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Effect"
        "500":
          description: Kan geen verbinding maken met de database of fout bij het uitvoeren van de query.
  /dbeffect:
    post:
      summary: Voeg een effect toe aan de database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EffectInput"
      responses:
        "200":
          description: Effect succesvol toegevoegd aan de database.
        "500":
          description: Kan geen verbinding maken met de database of fout bij het uitvoeren van de query.
components:
  schemas:
    Effect:
      type: object
      properties:
        id:
          type: string
          description: ID van het effect
          example: "9"
        name:
          type: string
          description: Naam van het effect
          example: "Rainbow"
        description:
          type: string
          description: Beschrijving van het effect
          example: "Displays rainbow colors along the whole strip"
    EffectInput:
      type: object
      properties:
        name:
          type: string
          description: Naam van het effect dat moet worden toegevoegd.
          example: "Nieuw Effect"
        effectData:
          type: array
          description: Array van effectgegevens.
          items:
            type: string
          example: ["waarde1", "waarde2", "waarde3"]
    Ledstrip:
      type: object
      properties:
        index:
          type: number
          description: Index van de LED-strip
          example: 1
        name:
          type: string
          description: Naam van de LED-strip
          example: "ic1"
        segments:
          type: array
          items:
            $ref: "#/components/schemas/Segment"
    Segment:
      type: object
      properties:
        start:
          type: number
          description: Startindex van het segment
        end:
          type: number
          description: Eindindex van het segment
          example: 11
        color:
          type: string
          description: Kleurcode in hexadecimale notatie
          example: "#ff0000"
          format: hex-color
