version: "3.8"

services:
  backend:
    container_name: backend
    build: ./Backend/
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - webserver
  website:
    container_name: website
    build: ./website/
    ports:
      - "80:8000"
    depends_on:
      - backend
    networks:
      - webserver
networks:
  webserver:
